# Generated by Django 3.2.13 on 2022-04-29 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.profile')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AdminNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.node')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.admin')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdminNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.adminnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.normaluser')),
            ],
        ),
        migrations.AddField(
            model_name='normaluser',
            name='granted_nodes',
            field=models.ManyToManyField(through='apis.UserAdminNode', to='apis.AdminNode'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.superadmin'),
        ),
        migrations.AddField(
            model_name='node',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.superadmin'),
        ),
        migrations.AddField(
            model_name='admin',
            name='granted_nodes',
            field=models.ManyToManyField(through='apis.AdminNode', to='apis.Node'),
        ),
        migrations.AddField(
            model_name='admin',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.superadmin'),
        ),
    ]
